# Site settings
title: Simon McDonnell
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonmcd.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
